In [25]:
import pandas as pd
import numpy as np
import json

In [2]:
df1 = pd.read_csv('diabetes_012_health_indicators_BRFSS2015.csv')
df2 = pd.read_csv('diabetes_binary_5050split_health_indicators_BRFSS2015.csv')
df3 = pd.read_csv('diabetes_binary_health_indicators_BRFSS2015.csv')

In [10]:


#0 = no  1 = yes, diabetes: 0=no diabetes, 1=prediabetes, 2=diabetes

df1.info()
df1.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 253680 entries, 0 to 253679
Data columns (total 22 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   Diabetes_012          253680 non-null  float64
 1   HighBP                253680 non-null  float64
 2   HighChol              253680 non-null  float64
 3   CholCheck             253680 non-null  float64
 4   BMI                   253680 non-null  float64
 5   Smoker                253680 non-null  float64
 6   Stroke                253680 non-null  float64
 7   HeartDiseaseorAttack  253680 non-null  float64
 8   PhysActivity          253680 non-null  float64
 9   Fruits                253680 non-null  float64
 10  Veggies               253680 non-null  float64
 11  HvyAlcoholConsump     253680 non-null  float64
 12  AnyHealthcare         253680 non-null  float64
 13  NoDocbcCost           253680 non-null  float64
 14  GenHlth               253680 non-null  float64
 15  MentHlth              253680 non-null  float64
 16  PhysHlth              253680 non-null  float64
 17  DiffWalk              253680 non-null  float64
 18  Sex                   253680 non-null  float64
 19  Age                   253680 non-null  float64
 20  Education             253680 non-null  float64
 21  Income                253680 non-null  float64
dtypes: float64(22)
memory usage: 42.6 MB

,Diabetes_012,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,HeartDiseaseorAttack,PhysActivity,Fruits,...,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income
count,253680.000000,253680.000000,253680.000000,253680.000000,253680.000000,253680.000000,253680.000000,253680.000000,253680.000000,253680.000000,...,253680.000000,253680.000000,253680.000000,253680.000000,253680.000000,253680.000000,253680.000000,253680.000000,253680.000000,253680.000000
mean,0.296921,0.429001,0.424121,0.962670,28.382364,0.443169,0.040571,0.094186,0.756544,0.634256,...,0.951053,0.084177,2.511392,3.184772,4.242081,0.168224,0.440342,8.032119,5.050434,6.053875
std,0.698160,0.494934,0.494210,0.189571,6.608694,0.496761,0.197294,0.292087,0.429169,0.481639,...,0.215759,0.277654,1.068477,7.412847,8.717951,0.374066,0.496429,3.054220,0.985774,2.071148
min,0.000000,0.000000,0.000000,0.000000,12.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000
25%,0.000000,0.000000,0.000000,1.000000,24.000000,0.000000,0.000000,0.000000,1.000000,0.000000,...,1.000000,0.000000,2.000000,0.000000,0.000000,0.000000,0.000000,6.000000,4.000000,5.000000
50%,0.000000,0.000000,0.000000,1.000000,27.000000,0.000000,0.000000,0.000000,1.000000,1.000000,...,1.000000,0.000000,2.000000,0.000000,0.000000,0.000000,0.000000,8.000000,5.000000,7.000000
75%,0.000000,1.000000,1.000000,1.000000,31.000000,1.000000,0.000000,0.000000,1.000000,1.000000,...,1.000000,0.000000,3.000000,2.000000,3.000000,0.000000,1.000000,10.000000,6.000000,8.000000
max,2.000000,1.000000,1.000000,1.000000,98.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,5.000000,30.000000,30.000000,1.000000,1.000000,13.000000,6.000000,8.000000

In [11]:
df2.describe()

,Diabetes_binary,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,HeartDiseaseorAttack,PhysActivity,Fruits,...,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income
count,70692.000000,70692.000000,70692.000000,70692.000000,70692.000000,70692.000000,70692.000000,70692.000000,70692.000000,70692.000000,...,70692.000000,70692.000000,70692.000000,70692.000000,70692.000000,70692.000000,70692.000000,70692.000000,70692.000000,70692.000000
mean,0.500000,0.563458,0.525703,0.975259,29.856985,0.475273,0.062171,0.147810,0.703036,0.611795,...,0.954960,0.093914,2.837082,3.752037,5.810417,0.252730,0.456997,8.584055,4.920953,5.698311
std,0.500004,0.495960,0.499342,0.155336,7.113954,0.499392,0.241468,0.354914,0.456924,0.487345,...,0.207394,0.291712,1.113565,8.155627,10.062261,0.434581,0.498151,2.852153,1.029081,2.175196
min,0.000000,0.000000,0.000000,0.000000,12.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000
25%,0.000000,0.000000,0.000000,1.000000,25.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,1.000000,0.000000,2.000000,0.000000,0.000000,0.000000,0.000000,7.000000,4.000000,4.000000
50%,0.500000,1.000000,1.000000,1.000000,29.000000,0.000000,0.000000,0.000000,1.000000,1.000000,...,1.000000,0.000000,3.000000,0.000000,0.000000,0.000000,0.000000,9.000000,5.000000,6.000000
75%,1.000000,1.000000,1.000000,1.000000,33.000000,1.000000,0.000000,0.000000,1.000000,1.000000,...,1.000000,0.000000,4.000000,2.000000,6.000000,1.000000,1.000000,11.000000,6.000000,8.000000
max,1.000000,1.000000,1.000000,1.000000,98.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,5.000000,30.000000,30.000000,1.000000,1.000000,13.000000,6.000000,8.000000

In [5]:
df3.head()

,Diabetes_binary,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,HeartDiseaseorAttack,PhysActivity,Fruits,...,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income
0,0.0,1.0,1.0,1.0,40.0,1.0,0.0,0.0,0.0,0.0,...,1.0,0.0,5.0,18.0,15.0,1.0,0.0,9.0,4.0,3.0
1,0.0,0.0,0.0,0.0,25.0,1.0,0.0,0.0,1.0,0.0,...,0.0,1.0,3.0,0.0,0.0,0.0,0.0,7.0,6.0,1.0
2,0.0,1.0,1.0,1.0,28.0,0.0,0.0,0.0,0.0,1.0,...,1.0,1.0,5.0,30.0,30.0,1.0,0.0,9.0,4.0,8.0
3,0.0,1.0,0.0,1.0,27.0,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,2.0,0.0,0.0,0.0,0.0,11.0,3.0,6.0
4,0.0,1.0,1.0,1.0,24.0,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,2.0,3.0,0.0,0.0,0.0,11.0,5.0,4.0

In [26]:

proportion = df2['Diabetes_binary'].value_counts(normalize=True) * 100
print("Proportion of Diabetes_binary (in %):")
print(proportion)

feature_statistics = df2.describe()
print("\nBasic Statistics for Features:")
print(feature_statistics)

Proportion of Diabetes_binary (in %):
Diabetes_binary
0.0    50.0
1.0    50.0
Name: proportion, dtype: float64

Basic Statistics for Features:
       Diabetes_binary        HighBP      HighChol     CholCheck  \
count     70692.000000  70692.000000  70692.000000  70692.000000
mean          0.500000      0.563458      0.525703      0.975259
std           0.500004      0.495960      0.499342      0.155336
min           0.000000      0.000000      0.000000      0.000000
25%           0.000000      0.000000      0.000000      1.000000
50%           0.500000      1.000000      1.000000      1.000000
75%           1.000000      1.000000      1.000000      1.000000
max           1.000000      1.000000      1.000000      1.000000

                BMI        Smoker        Stroke  HeartDiseaseorAttack  \
count  70692.000000  70692.000000  70692.000000          70692.000000
mean      29.856985      0.475273      0.062171              0.147810
std        7.113954      0.499392      0.241468              0.354914
min       12.000000      0.000000      0.000000              0.000000
25%       25.000000      0.000000      0.000000              0.000000
50%       29.000000      0.000000      0.000000              0.000000
75%       33.000000      1.000000      0.000000              0.000000
max       98.000000      1.000000      1.000000              1.000000

       PhysActivity        Fruits  ...  AnyHealthcare   NoDocbcCost  \
count  70692.000000  70692.000000  ...   70692.000000  70692.000000
mean       0.703036      0.611795  ...       0.954960      0.093914
std        0.456924      0.487345  ...       0.207394      0.291712
min        0.000000      0.000000  ...       0.000000      0.000000
25%        0.000000      0.000000  ...       1.000000      0.000000
50%        1.000000      1.000000  ...       1.000000      0.000000
75%        1.000000      1.000000  ...       1.000000      0.000000
max        1.000000      1.000000  ...       1.000000      1.000000

            GenHlth      MentHlth      PhysHlth      DiffWalk           Sex  \
count  70692.000000  70692.000000  70692.000000  70692.000000  70692.000000
mean       2.837082      3.752037      5.810417      0.252730      0.456997
std        1.113565      8.155627     10.062261      0.434581      0.498151
min        1.000000      0.000000      0.000000      0.000000      0.000000
25%        2.000000      0.000000      0.000000      0.000000      0.000000
50%        3.000000      0.000000      0.000000      0.000000      0.000000
75%        4.000000      2.000000      6.000000      1.000000      1.000000
max        5.000000     30.000000     30.000000      1.000000      1.000000

                Age     Education        Income
count  70692.000000  70692.000000  70692.000000
mean       8.584055      4.920953      5.698311
std        2.852153      1.029081      2.175196
min        1.000000      1.000000      1.000000
25%        7.000000      4.000000      4.000000
50%        9.000000      5.000000      6.000000
75%       11.000000      6.000000      8.000000
max       13.000000      6.000000      8.000000

[8 rows x 22 columns]

In [27]:
correlations = df2.corr(method='pearson')['Diabetes_binary'].sort_values(ascending=False)
print("\nCorrelations with Diabetes_binary:")
print(correlations)

Correlations with Diabetes_binary:
Diabetes_binary         1.000000
GenHlth                 0.407612
HighBP                  0.381516
BMI                     0.293373
HighChol                0.289213
Age                     0.278738
DiffWalk                0.272646
PhysHlth                0.213081
HeartDiseaseorAttack    0.211523
Stroke                  0.125427
CholCheck               0.115382
MentHlth                0.087029
Smoker                  0.085999
Sex                     0.044413
NoDocbcCost             0.040977
AnyHealthcare           0.023191
Fruits                 -0.054077
Veggies                -0.079293
HvyAlcoholConsump      -0.094853
PhysActivity           -0.158666
Education              -0.170481
Income                 -0.224449
Name: Diabetes_binary, dtype: float64

In [30]:

if 'Sex' in df2.columns:
    subgroup_by_sex = df2.groupby('Sex')['Diabetes_binary'].mean() * 100
    print("\nDiabetes Prevalence by Sex (in %):")
    print(subgroup_by_sex)


if 'Age' in df2.columns:
    subgroup_by_age = df2.groupby('Age')['Diabetes_binary'].mean() * 100
    print("\nDiabetes Prevalence by Age (in %):")
    print(subgroup_by_age)

if 'Education' in df2.columns:
    subgroup_by_education = df2.groupby('Education')['Diabetes_binary'].mean() * 100
    print("\nDiabetes Prevalence by Education (in %):")
    print(subgroup_by_education)

if 'Income' in df2.columns:
    subgroup_by_income = df2.groupby('Income')['Diabetes_binary'].mean() * 100
    print("\nDiabetes Prevalence by Income (in %):")
    print(subgroup_by_income)

Diabetes Prevalence by Sex (in %):
Sex
0.0    47.962799
1.0    52.420603
Name: Diabetes_binary, dtype: float64

Diabetes Prevalence by Age (in %):
Age
1.0      7.967314
2.0     10.028653
3.0     15.324549
4.0     22.413176
5.0     29.857955
6.0     37.478485
7.0     44.935972
8.0     49.552482
9.0     56.695016
10.0    60.408990
11.0    63.910990
12.0    63.088617
13.0    59.141172
Name: Diabetes_binary, dtype: float64

Diabetes Prevalence by Education (in %):
Education
1.0    62.666667
2.0    71.827565
3.0    66.608645
4.0    56.827402
5.0    51.692461
6.0    39.969254
Name: Diabetes_binary, dtype: float64

Diabetes Prevalence by Income (in %):
Income
1.0    65.992800
2.0    68.608270
3.0    64.207306
4.0    60.889156
5.0    56.229713
6.0    51.433849
7.0    46.083151
8.0    34.849365
Name: Diabetes_binary, dtype: float64